apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: mnv1e98jl-go 
  janus-idp.io/tekton: mnv1e98jl-go
  backstage.io/kubernetes-id: mnv1e98jl-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: mnv1e98jl-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  