apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: mnv1e98jl-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mnv1e98jl-go 
  name: mnv1e98jl-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: mnv1e98jl-go 
